### ISSUE TITLE
Template out HTTP requests

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#10]
**Intent:**
Our snippet must communicate with an api at some point, to achieve it's full functionality. Let's template out some code that will eventually achieve this if / when we get a server.

**What you should know:**
- how to use fetch,
- how to mock data / or create a little tiny server for the sake of testing. 

We'll need to set up some functions in our pipeline to perform two basic HTTP requests: `GET` and `POST`. 

Somewhere near the beginning of our function pipe we will be making an HTTP request to get the emojion bars for the current user's site.

Somewhere else we'll need to set up a function that is set to fire whenever a user clicks on an emoji to fire it off.

**Comment by venomnert** [comment]
I will like to work on this issue

**Comment by teesloane** [comment]
Some good work on this issue is happening over [here](https://github.com/the-heap/Emojions/issues/43)
