### ISSUE TITLE
Setup circleCI

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#11]
We should have some kind of continuous integration so people can automatically run tests when pushing code.

**Comment by mackiedrew** [comment]
Dibs!

**Comment by mackiedrew** [comment]
I think we should add Jest for testing first, otherwise its kind of needless.

**Comment by teesloane** [comment]
Yep we can wait on #12 , but don't let that hold you up 😸

**Comment by mihok** [comment]
Yeah add it in now and we can enjoy passing tests every time until tests are added 😀

**Comment by mackiedrew** [comment]
- [ ] Add circle.yml to root
- [ ] Add some integration for client
- [ ] Add some integration for snippet
- [ ] Add CodeCov to CircleCI
