### ISSUE TITLE
Setup JEST

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#12]
we will use JEST for writing unit tests. This requires the following

- [ ] install jest
- [ ] set up a methodology for testing (ie. should we use a seperate folder? have a `*.spec.js` for each js file in parallel?
- [ ] adding information to our README for how to run tests

**Comment by mackiedrew** [comment]
I've always used `*.test.js`, What does `*.spec.js` stand for? I'm not sold on either, just curious. :smile:

**Comment by teesloane** [comment]
I actually don't know exactly why it's `spec` ; i figure `specification` is relatively synonymous with `test` heh. Maybe someone else can weigh in on this...

**Comment by mackiedrew** [comment]
I'll do jest too I suppose. I love the tooling stuff!
