### ISSUE TITLE
refactor the `pipe` function to be more readable

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#14]
Currently our `pipe` function looks something like this:

```javascript

  /**
   * create a function pipe.
   * TODO: refactor to be more readable. PLEASE.
   * @param {functions} funs -> unknown number of functions
   * @returns - a state object. 
   */
  function pipe(...funs) {
    return funs.reduce(
      (f, g) => (...args) => g(f(...args))
    )
  }
```

This is super, not-readable (to me). I mostly ripped it straight from [this blog](http://vanslaars.io/post/create-pipe-function/). (bad form! copy pasting code!)

The new function should try and be more explicit — with names that are more relevant to `.reduce` (no using `f, g`.)

**Comment by mackiedrew** [comment]
```javascript  
/**
   * The All Magical, Beautiful Function Pipe!
   * Creates a function which will run a series of functions into one another in the provided order.
   * Since it returns a function, this can be reused as a function provided with new arguments.
   * @param {Function} functions An unknown number of functions, add as many as you want a
   * arguments as required.
   * @returns A single function that can be run to run all provided functions on given data in the
   * originally provided order.
   */

  function pipe(...functions) {
    return functions.reduce((functionPipeSoFar, nextFunction) => (...arguments) =>
      nextFunction(functionPipeSoFar(...arguments)));
  }
```

**Comment by mackiedrew** [comment]
Just leaving this here for storage. I don't wanna make a new branch right now, but I will later.

**Comment by teesloane** [comment]
This is excellent. This is what a doc comment should look like!

You also caught a mistake I made - the function does not return a `state` object; it returns a function, that when invoked _should be_ our state object. 

The only mistake I think that remains is that the `@param {function}` should really be `@param {Array}` .... I think?

Thanks @mackiedrew

**Comment by mackiedrew** [comment]
Thanks! The pipe() function creates nested functions rather than an array. This is why you can later invoke it:

```javascript
  const render = pipe(
    getAllIds,
    makeEmojionBars,
    makeContainers,
    populateContainers
  )(state);
```

One of the tests for the `pipe()` checks that it is returning a function:
![tests](https://cloud.githubusercontent.com/assets/20718044/25626297/15dd4942-2f2d-11e7-96a9-761df6706004.png)

**Comment by teesloane** [comment]
Looks great!

**Comment by mackiedrew** [comment]
Oh sorry I misread your comment! You are right, it should be an array... or... how do you do a unknown number of params in JSDocs?

**Comment by teesloane** [comment]
Not too sure, haven't looked into. I've been relatively informat with my js-doc'ing. Maybe it doesn't recognize `...args` at this point in time.. Not the biggest problem though...
