### ISSUE TITLE
Research Elm Emoji Packages

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#18]

**Comment by mihok** [comment]
How are the emoji's being loaded on the snippet, will they be unicode, font, image?

**Comment by teesloane** [comment]
I actually have no clue so far. Up until now, I've just been copying and pasting from the mac emoji keyboard (which is launched by hitting `control + command + space`. 

any ideas on this?

**Comment by mackiedrew** [comment]
Yeah, it's Unicode right now, which, on Linux, doesn't look so hot. Here is my thought... SVG? With SVG images we could convert them to relatively simple shapes that can be less than 200 characters long then we could use javascript to inject the emoji's and store them in the source or transmit them easily over a request. That prevents the monotone of a font. The very narrow usability of (good looking) Unicode emoji's and is better optimised and adaptable than images.

**Comment by teesloane** [comment]
Interesting. One Q:

> That prevents the monotone of a font.

what do you mean by this?

---

I actually know very little about emojis as a text entity, or whatever you want to call it. I definitely have a few emojis assumptions. Reading [this wiki article](https://en.wikipedia.org/wiki/Emoji#Implementation) seems to confirm that emoji's are just unicode symbols, and then interpreted by different fonts.

from the article; regarding chrome **os** (not browser?)
>Chrome OS, through its inclusion of the Noto fonts, supports the emoji set introduced through Unicode 6.2. As of Chrome OS 41, Noto Color Emoji is the default font for most emoji.

So, I found [this repo](https://github.com/googlei18n/noto-emoji) which is an offline version of noto for emojis.  There's also the [noto google font](https://fonts.google.com/specimen/Noto+Sans).

Is there any chance that we can build `snippet` to reference/include the `noto google font` and defer all emoji instances (which are just unicode, if I understand correctly) to use the `font-family: noto` for css?

Even if that online google font doesn't have unicode emojis, we could maybe find a way to get a `ttf` online in the cloud somewhere ...
