### ISSUE TITLE
Generate a snippet for a user to install

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#20]

**Comment by mihok** [comment]
How will the snippet code pull in the configuration? 

Will the snippet script be rebuilt with just the emojis requested inserted in? This solution would require some sort of template key in the snippet script. Or,

Will the snippet receive the emojis via say a get parameter: `/path/to/script/emojions.js?use=grin,smile,plus-one`. Or,

Did you have another solution in mind?

**Comment by teesloane** [comment]
I actually have no idea what to do here yet. I'm very open to suggestions. At first thought, I just kind of thought that the snippet would be loaded into the `client` as a string, that, on interacting with the `client` (ie. choosing your emojis, the endpoint where it stores the counts etc), it would then just run a `.replace` on the parts of the snippet string that need to be updated (which, after refactoring `snippet` should just be a few variables I think.

Thoughts
