### ISSUE TITLE
Simplify the example html page

### ISSUE THREAD

**Issue by mihok** [the-heap/Emojions#28]
This `snippet/example.html` looks like its been borrowed from somewhere, its also pretty daunting as someone just joining the project. Lets simplify the page and highlight a common use case for Emojions while we're at it.

I propose that we have a simple article comments section as a common use case (we can build out more examples later, and possibly in the client?)

The objective here is to make the `example.html` dead simple.

**Comment by teesloane** [comment]
This is a great idea. I'm assigning this to you because you are awesome and right next to me.
