### ISSUE TITLE
Dont require unique IDs to add emojions to a DOM element.

### ISSUE THREAD

**Issue by mihok** [the-heap/Emojions#29]
Today, we have to add `<element id="emojions_someuniquestring">` for each area we want to add Emojions to. This seems a bit unnecessary, we probably want to search for `.emojions` or something to that effect as a class name rather than a unique ID.

**Comment by teesloane** [comment]
Yes, this is absolutely true. Now that we are simplifying our `example.html` page this should be even more clear / simple to setup.

**Comment by teesloane** [comment]
This is being addressed!

**Comment by broneks** [comment]
also maybe make the unique ID configurable?

**Comment by teesloane** [comment]
>so maybe make the unique ID configurable?

Yes, this should probably happen on the elm side for when a user configures their snippet...

**Comment by teesloane** [comment]
Closing this because @venomnert has done some great work on this!
