### ISSUE TITLE
Add .editorconfig to unify coding standards

### ISSUE THREAD

**Issue by ChristofLee** [the-heap/Emojions#36]
## Detailed Description
Use [Editor Config](http://editorconfig.org/) to define a coding standard and prevent whitespace changes in git PR's between different developers. 

## Possible Implementation
Here's a possible config for our purposes:
```
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 2

[*.txt]
indent_style = tab
indent_size = 4
```

**Comment by ChristofLee** [comment]
I'm sorry this is a bit **bike-shed**y, but I think it would benefit us in the long run (this month I guess). 

If this is of interest, I will happily write a more concise config and create a PR.

**Comment by teesloane** [comment]
hmm interesting idea. I think these files might need to be setup as they correspond to the JS auto formatter (prettier) and elm format and there differences... happy to have you make a PR and we can all test and see how things go :)

**Comment by ChristofLee** [comment]
Awesome, will look into it 👍

**Comment by ChristofLee** [comment]
I have created a PR for this issue: https://github.com/the-heap/Emojions/pull/38
