### ISSUE TITLE
Manage the state of an emoji bar

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#5]
Our state object is going to be passed down from function to function in our function pipe (see #3 if unfamiliar.

Our state will probably look something like this:

```javsacript

  var state = {
    emojis    : {},
    dom       : { mounts: [], containers: []},
  }
```

There are two main pieces of "state" in our snippet:

1. Our emojis and their counts. ("emojis")
> This is our _data_ — eventually will live in a database, and we will get / send it with network requests
2. The emoji's displaying in the dom. ("dom").
> At the lowest level - this is just a UI - a visual display of our data.

Somehow we connect the two - and for now we won't worry about how network requests would come in (ie. getting this data form a database or sending it to one). For now we just want the following to happen: click an emoji and update the state, whenever the state updates, re render the dom elements.
/Here's some pseudo code for what we'll want to do:

- Write a function that adds a click-event listener to _every_ emoji in every emojion bar.
  - using the state[dom] object, loop through all our containers that have an emoji bar
    - for each container - loop through all the emojis, and add a unique event listeners to each one
    - the event listener listens for 'click' events, and needs to , on click , increment the count for _that specific_ emoji.

**Comment by ericbastarache** [comment]
Hey, I'm claiming this issue

**Comment by teesloane** [comment]
This was closed recently! Thanks for your hard work @ericbastarache !
