### ISSUE TITLE
Setup Flask for our backend

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#50]
**Read this to:**

Brainstorm / Think about how to setup flask.

**I expect you to know:**

[Our API roadmap](https://github.com/the-heap/Emojions/issues/54)

## General Thoughts

- we could probably create a single line flask file for the server. It might be nice to have a very simple application; keeping it as short as possible. I would like to consider this possibility; and start to break things out into separate files when we need to. 
- I don't think there is any need to have authentication that I know of...
- We need to figure out some kind of database solution; and I'm not sure what that is yet. #52

**Comment by quietcoding** [comment]
Agreed, lets just keep the server routing of flask to a minimum. I'll throw something together if no one's had a stab at it yet.

**Comment by teesloane** [comment]
Sounds good — would love to have you tackle that. Right now I'm looking into docker for making this whole dev environment easier to setup, so I'm excited to add python/flask to that (if I can get it working ..)
