### ISSUE TITLE
Decide on a database we can use with Flask

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#52]
Any thoughts on this @qazqwezxc ? I have more experience with sqlalcehmy with flask than any nosql choices, but I'm open to whatever! Ideally whatever we choose is simple and not too hard to set up and document.

**Comment by quietcoding** [comment]
I've had experience in PostgreSQL since I've read articles on how inferior MySQL is to PostgreSQL. That said, I've never done it with sqlalchemy, so I'm open to that idea. What about SQLite? It seems like it stems from the flask tutorials and it would be a matter of implementation for our purpose.

**Comment by teesloane** [comment]
SQLite makes a ton of sense. Let's go with that!
small, simple, easy (I imagine?) to migrate to postgres if necessary!
