### ISSUE TITLE
Create endpoint that fetches emojion data by unique user information

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#53]
**Read this to:**

Figure out how to tackle the data fetching for the emojion bar from front end to back end.

**I expect you to know:**

Our general [roadmap](https://github.com/the-heap/Emojions/issues/1) 
[Our API roadmap](https://github.com/the-heap/Emojions/issues/54)

# User Flow + To Dos:
- A user opens their site which has the snippet installed
  - [ ] The snippet scans for all instances of the emojion bar based on the `EMOJION_ID` constant
  - [ ] Sends requests to api with a payload of all the emojion instances for the current page.
  - [ ] Flask receives req, queries DB
    - [ ] If the DB does not have an instance of the emojion bar for that value, _create one_ and initialize it's values
    - [ ] IF the db does have the values, return them!

**Comment by teesloane** [comment]
@qazqwezxc I'm assigning you this in case you're interested + I'd appreciate any thoughts you have on the flow above!

**Comment by quietcoding** [comment]
Working on it now, I think I need to restructure the current data structure.

**Comment by teesloane** [comment]
What are you thinking? The data structure on the front end or the back end?

**Comment by quietcoding** [comment]
I'm not sure if what is currently written under emoji is correctly structured for each emojion bar?

I was thinking it should be like:

emoji_bar#1 --> peak #, face #, rocket #, etc
emoji_bar#2 --> peak #, face #, rocket #, etc

It's currently set up that you have each emoji icon has a unique identity on top of the emoji bar? Is that what we're trying to achieve?

**Comment by teesloane** [comment]
Yeah, each emoji icon needs to have it's own count + id; so yes, it's yet another nested object — this is necessary to be able to target the html dom elements that correspond to each single emoji — does that make sense ? 

The comment for `populateContainers` in `index.js` kind of explains the need for this data struct on the front end.
