### ISSUE TITLE
Create a stylesheet and append it to the DOM.

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#7]
Read this to:
Help out with setting up styling the emojion bar

I expect you to know:
how we are architecting the data flow in this app. Please read #3 

Just like our snippet itself is added to the DOM by a user, we need the _snippet_ to create a stylesheet that styles the classnames of our emojion bar. A `<style>` tag is quite similar to a `<div>` or a `<span`> in that they can both be created using javascript.

To do this, here are a few hints:

- you need to create a new function and add it to our `pipe` function
- It probably makes sense to put this function at the top of the pipe.
- if you are unsure how to create a dom element with javascript check out the `makeContainers` function.

If this issue appeals to you, please assign it to yourself and comment to let others know you want to work on it.

**Comment by ericbastarache** [comment]
Hey, I'd like to work on this issue

**Comment by teesloane** [comment]
Sounds good! I'll assign you to it! Feel free chat in the gitter if you run into any blocks; and thanks for joining!
