### ISSUE TITLE
Adaptive Styling

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#8]
This issue requires that #7 be completed.

After someone has generated a style sheet to style our snippets, we can go ahead and actually style them!

Notes: 

- let's use flexbox
- aim for a responsive design (our wireframe does not have a mockup for that, so use your imagination!
- remember to test on elements of different size.

I would like to remind you our basic wireframe for this styling!

![](https://cloud.githubusercontent.com/assets/12987958/25552246/a334ed2c-2c62-11e7-8e6c-ba123b1bc231.png)

**Comment by ChristofLee** [comment]
I'm gonna have a crack at this over the next few hours. 

Will post an update.

**Comment by teesloane** [comment]
Excellent, thanks for coming on board @ChristofLee!

**Comment by ChristofLee** [comment]
My PR for this issue is ready for review:
https://github.com/the-heap/Emojions/pull/37

**Comment by teesloane** [comment]
Excellent work. merged + 🚢 !
